baseURL = 'https://idnod.github.io/olk-idnod-post-app/'
languageCode = 'es'
title = 'Lherc Links'

[params]
  description = "My personal links page"
  author = "Lherc"
  profileImage = "images/profile.jpg"
  
  [[params.links]]
  id = "github"
  title = "GitHub"
  description = "My code and projects"
  url = "https://github.com/lherc"
  icon = "fab fa-github"
  image = "images/github.jpg"
  
  [[params.links]]
  id = "linkedin"
  title = "LinkedIn"
  description = "My professional profile"
  url = "https://linkedin.com/in/lherc"
  icon = "fab fa-linkedin"
  image = "images/linkedin.jpg"
  
  [[params.links]]
  id = "twitter"
  title = "Twitter"
  description = "My thoughts and updates"
  url = "https://twitter.com/lherc"
  icon = "fab fa-twitter"
  image = "images/twitter.jpg"
  
  [[params.links]]
  id = "portfolio"
  title = "Portfolio"
  description = "My projects and work"
  url = "https://lherc.dev"
  icon = "fas fa-briefcase"
  image = "images/portfolio.jpg"
  
  [[params.links]]
  id = "blog"
  title = "Blog"
  description = "Articles and tutorials"
  url = "https://blog.lherc.dev"
  icon = "fas fa-blog"
  image = "images/blog.jpg"
  
  [[params.links]]
  id = "email"
  title = "Email"
  description = "Contact me directly"
  url = "mailto:hola@lherc.dev"
  icon = "fas fa-envelope"
  image = "images/email.jpg"

  # Certifications Section
  [[params.certifications]]
  id = "aws-certified"
  title = "AWS Certified Solutions Architect"
  description = "Professional certification in AWS cloud solutions architecture"
  icon = "fab fa-aws"
  image = "images/aws-certification.jpg"
  date = "2023-12-15"
  
  [[params.certifications]]
  id = "google-cloud-certified"
  title = "Google Cloud Professional"
  description = "Professional certification in Google Cloud Platform"
  icon = "fab fa-google"
  image = "images/gcp-certification.jpg"
  date = "2023-10-20"

  # Products Section
  [[params.products]]
  id = "mobile-app"
  title = "Mobile App Suite"
  description = "Cross-platform mobile application with advanced features"
  url = "https://github.com/lherc/mobile-app"
  icon = "fas fa-mobile-alt"
  image = "images/mobile-product.jpg"
  tech = ["React Native", "TypeScript", "Firebase"]
  
  [[params.products]]
  id = "web-platform"
  title = "Web Platform"
  description = "Scalable web platform with modern architecture"
  url = "https://github.com/lherc/web-platform"
  icon = "fas fa-globe"
  image = "images/web-product.jpg"
  tech = ["Next.js", "PostgreSQL", "Docker"]

  # Organizations Section
  [[params.organizations]]
  id = "tech-community-lead"
  title = "Tech Community Lead"
  description = "Leader of the local tech community"
  organization = "Tech Community Hub"
  icon = "fas fa-users"
  image = "images/tech-community.jpg"
  role = "Leader"
  period = "2022 - Present"
  
  [[params.organizations]]
  id = "open-source-contributor"
  title = "Open Source Contributor"
  description = "Active contributor to open source projects"
  organization = "Mozilla Foundation"
  icon = "fab fa-firefox-browser"
  image = "images/mozilla-contributor.jpg"
  role = "Contributor"
  period = "2021 - Present"
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
